export const SCREENS = {
  HOME: "HOME",
  GET_STARTED: "GET_STARTED",
  GRANT_ACCESS: "GRANT_ACCESS",
  EVENT_DETAILS: "EVENT_DETAILS",
  NEW_CALENDAR: "NEW_CALENDAR",
} as const;

export const STORAGE = {
  HAS_LAUNCHED: "HAS_LAUNCHED",
};

export const SUPPORTED_LANGS = {
  FR: "fr-US",
  EN: "en-US",
};

export const CALENDAR_REDUCER_TYPES = {
  SET_CURRENT_DATE: "SET_CURRENT_DATE",
  SET_CURRENT_CALENDAR_ID: "SET_CURRENT_CALENDAR_ID",
  SET_DEFAULT_CALENDAR_ID: "SET_DEFAULT_CALENDAR_ID",
  UPDATE_CALENDARS: "UPDATE_CALENDARS",
};
